apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: pubsub
  namespace: iotea
spec:
  type: pubsub.mqtt
  version: v1
  metadata:
  - name: url
    value: "tcp://mosquitto:1883"
  - name: qos
    value: 1
  - name: retain
    value: "true"
  - name: cleanSession
    value: "false"
