version: '3.6'
services:
  
  test_set_cpp:
    build:
      context: ..
      labels:
        iotea.iotea.version: "0.6.0"
      dockerfile: ./docker/integration-tests/cpp-test-suite/test_suite/Dockerfile.${ARCH}
      args:
        - HTTP_PROXY=${DOCKER_HTTP_PROXY}
        - HTTPS_PROXY=${DOCKER_HTTPS_PROXY}
        - INTEGRATION_TEST_PATH=${INTEGRATION_TEST_DIR}/sdk-test-suites/cpp
    networks:
      - iotea-platform-network

  test_fnc_cpp:
    build:
      context: ..
      labels:
        iotea.iotea.version: "0.6.0"
      dockerfile: ./docker/integration-tests/cpp-test-suite/test_fnc/Dockerfile.${ARCH}
      args:
        - HTTP_PROXY=${DOCKER_HTTP_PROXY}
        - HTTPS_PROXY=${DOCKER_HTTPS_PROXY}
        - INTEGRATION_TEST_PATH=${INTEGRATION_TEST_DIR}/sdk-test-suites/cpp
    networks:
      - iotea-platform-network

networks:
  iotea-platform-network:
    name: iotea-platform-network
    driver: bridge