version: '3.6'
services:
  
  test_runner_all:
    build:
      context: ..
      labels:
        iotea.iotea.version: "0.5.0"
      dockerfile: ./docker/integration-tests/javascript/test_runner/Dockerfile.${ARCH}
      args:
        - HTTP_PROXY=${DOCKER_HTTP_PROXY}
        - HTTPS_PROXY=${DOCKER_HTTPS_PROXY}
        - INTEGRATION_TEST_PATH=${INTEGRATION_TEST_DIR}/runner/javascript
    networks:
      - iotea-platform-network

networks:
  iotea-platform-network:
    name: iotea-platform-network
    driver: bridge