@startuml
/'
  Copyright (c) 2021 Bosch.IO GmbH

  This Source Code Form is subject to the terms of the Mozilla Public
  License, v. 2.0. If a copy of the MPL was not distributed with this
  file, You can obtain one at https://mozilla.org/MPL/2.0/.

  SPDX-License-Identifier: MPL-2.0
'/

    skinparam backgroundColor #FFFFF

    right footer "IoT Event Analytics Version: 0.5"

    actor "Provider" as Provider

    participant Platform as Platform #LightBlue

    participant Middleware as Middleware #LightSlateGray

    participant TalentA as TalentA #LightGreen
    participant TalentB as TalentA #LightGreen

    group External Feature Ingestion (TalentA is Subscriber)
        Provider ->> Middleware: IngestionMsg \n [INGESTION_TOPIC]
        Middleware ->> Platform: IngestionMsg \n [INGESTION_TOPIC]
        Platform ->> Middleware: FeatureEventMsg \n [<TALENTA_TOPIC>]
        Middleware ->> TalentA: FeatureEventMsg \n [<TALENTA_TOPIC>]
        TalentA -> TalentA: OnEvent()
    end

    group Internal Feature Ingestion (TalentA is Provider, Talent B is Subscriber)
        TalentA ->> Middleware: IngestionMsg \n [INGESTION_TOPIC]
        Middleware ->> Platform: IngestionMsg \n [INGESTION_TOPIC]
        Platform ->> Middleware: FeatureEventMsg \n [<TALENTB_TOPIC>]
        Middleware ->> TalentB: FeatureEventMsg \n [<TALENTB_TOPIC>]
        TalentB -> TalentB: OnEvent()
    end
@enduml