name: Build Docker images

on:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          driver-opts: network=host
      - name: Build IoTEA-Configmanager (linux/amd64)
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          platforms: linux/amd64
          tags: localhost:5000/iot-event-analytics/configmanager-amd64:latest
          file: docker/config/Dockerfile.amd64
      - name: Build IoTEA-Configmanager (linux/arm64)
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          platforms: linux/arm64
          tags: localhost:5000/iot-event-analytics/configmanager-arm64:latest
          file: docker/config/Dockerfile.arm64
      - name: Build IoTEA-Pipeline (linux/amd64)
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          platforms: linux/amd64
          tags: localhost:5000/iot-event-analytics/pipeline-amd64:latest
          file: docker/pipeline/Dockerfile.amd64
      - name: Build IoTEA-Pipeline (linux/arm64)
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          platforms: linux/arm64
          tags: localhost:5000/iot-event-analytics/pipeline-arm64:latest
          file: docker/pipeline/Dockerfile.arm64
      - name: Build IoTEA-Platform Slim (linux/amd64)
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          platforms: linux/amd64
          tags: localhost:5000/iot-event-analytics/platform-amd64:latest
          file: docker/platform/Dockerfile.slim.amd64
      - name: Build IoTEA-Platform Slim (linux/arm64)
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          platforms: linux/arm64
          tags: localhost:5000/iot-event-analytics/platform-arm64:latest
          file: docker/platform/Dockerfile.slim.arm64
