name: Build Docker images

on:
  workflow_dispatch:
    inputs:
      doPerformPush:
        description: 'Perform Docker Push'
        required: true
        default: 'false'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          driver-opts: network=host
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}      
      - name: Build IoTEA-Configmanager (linux/amd64)
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64
          push: ${{ env.INPUT_DOPERFORMPUSH }}
          tags: | 
            ${{ env.IMAGE_NAME }}/configmanager-amd64:latest
            ghcr.io/${{ env.IMAGE_NAME }}/configmanager-amd64:latest
          file: docker/config/Dockerfile.amd64
      - name: Build IoTEA-Configmanager (linux/arm64)
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/arm64
          push: ${{ env.INPUT_DOPERFORMPUSH }}
          tags: | 
            ${{ env.IMAGE_NAME }}/configmanager-arm64:latest
            ghcr.io/${{ env.IMAGE_NAME }}/configmanager-arm64:latest
          file: docker/config/Dockerfile.arm64
      - name: Build IoTEA-Pipeline (linux/amd64)
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64
          push: ${{ env.INPUT_DOPERFORMPUSH }}
          tags: | 
            ${{ env.IMAGE_NAME }}/pipeline-amd64:latest
            ghcr.io/${{ env.IMAGE_NAME }}/pipeline-amd64:latest
          file: docker/pipeline/Dockerfile.amd64
      - name: Build IoTEA-Pipeline (linux/arm64)
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/arm64
          push: ${{ env.INPUT_DOPERFORMPUSH }}
          tags: | 
            ${{ env.IMAGE_NAME }}/pipeline-arm64:latest
            ghcr.io/${{ env.IMAGE_NAME }}/pipeline-arm64:latest
          file: docker/pipeline/Dockerfile.arm64
      - name: Build IoTEA-Platform Slim (linux/amd64)
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64
          push: ${{ env.INPUT_DOPERFORMPUSH }}
          tags: | 
            ${{ env.IMAGE_NAME }}/platform-amd64:latest
            ghcr.io/${{ env.IMAGE_NAME }}/platform-amd64:latest
          file: docker/platform/Dockerfile.slim.amd64
      - name: Build IoTEA-Platform Slim (linux/arm64)
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/arm64
          push: ${{ env.INPUT_DOPERFORMPUSH }}
          tags: | 
            ${{ env.IMAGE_NAME }}/platform-arm64:latest
            ghcr.io/${{ env.IMAGE_NAME }}/platform-arm64:latest
          file: docker/platform/Dockerfile.slim.arm64
