name: Integration test

on: [push, pull_request]

jobs:
  integration_test:
    runs-on: ubuntu-latest
    name: Run integration test

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: Setup & start platform
      working-directory: ${{github.workspace}}/docker-compose
      shell: bash
      # Build & run platform.
      # It's run daemonized (docker-compose -d) since a running platform
      # is needed later in the "Run integration tests" step
      run: docker-compose -f docker-compose.mosquitto.yml -f docker-compose.platform.yml --env-file .env up --build -d

    - name: Build Node.js SDK
      working-directory: ${{github.workspace}}
      shell: bash
      run: |
        yarn --frozen-lockfile

    - name: Build Python SDK
      working-directory: ${{github.workspace}}/test/integration-tests
      shell: bash
      env:
        IOTEA_PROJECT_ROOT: ${{github.workspace}}
      run: |
        python3 -m venv .venv
        source .venv/bin/activate
        python -m pip install wheel
        python -m pip install $IOTEA_PROJECT_ROOT/src/sdk/python/src --force

    - name: Build C++ tests
      working-directory: ${{github.workspace}}/test/integration-tests/testset_sdk/cpp
      shell: bash
      run: |
        cmake -B build -S .
        cmake --build build --parallel

    - name: Run integration tests
      working-directory: ${{github.workspace}}/test/integration-tests
      shell: bash
      # The required "test talents" are started manually as background
      # jobs before finally invoking the test runner.
      run: |
        ./testset_sdk/cpp/build/function_provider_for_test 2>&1 >/dev/null &
        ./testset_sdk/cpp/build/testset_sdk 2>&1 >/dev/null &
        source .venv/bin/activate
        python ./testset_sdk/python/test_set_sdk.py 2>&1 >/dev/null &
        python ./testset_sdk/python/function_provider.py 2>&1 >/dev/null &
        node ./testset_sdk/javascript/functionProvider.js 2>&1 >/dev/null &
        node ./testset_sdk/javascript/eventTester.js 2>&1 >/dev/null &
        node ./testset_sdk/javascript/testSetSDK.js 2>&1 >/dev/null &
        node ./runner/javascript/test_runner.js
      timeout-minutes: 1

